In [3]:
import tensorflow as tf
import numpy as np

create constant

In [4]:
x = tf.constant(np.random.rand(32))
y = tf.constant([1,2,3])

start a session object

In [7]:
sess =  tf.Session()
x_data = np.array([[1,2,3],[4,5,6]])
x_tensor = tf.convert_to_tensor(x_data,dtype=tf.float32)

sess.run(x_tensor)


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)

In [11]:
vari = tf.Variable(tf.zeros([100]))

protobuffer 

In [18]:
g = tf.Graph() 
with g.as_default(): 
    sess = tf.Session() 
    W_m = tf.Variable(tf.zeros([10, 5])) 
    x_v = tf.placeholder(tf.float32, [None, 10]) 
    result = tf.matmul(x_v, W_m) 
    print(g.as_graph_def()) 

node {
  name: "zeros"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
          dim {
            size: 5
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "Variable"
  op: "Variable"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 10
        }
        dim {
          size: 5
        }
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "zeros"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
  

### Simple matrix operations

In [26]:
sess = tf.InteractiveSession()

x = tf.constant( [ [1,46,8,2],[98,53,12,4],[5,3,13,6],[35,2,87,1]  ])
y = tf.constant( [ [23,6,1,7],[12,3,7,2],[4,3,23,8],[3,2,7,6] ])

floatx = tf.constant([[23.,6.,1.,7.],[12.,3.,7.,2.],[4.,3.,23.,8.],[3.,2.,7.,6.] ])

print(tf.transpose(y).eval())

print("---matmul---")
print(tf.matmul(x,y).eval())

print("--matrix determinant--")
print(tf.matrix_determinant(floatx).eval())

print("----matrix solve----")
print(tf.matrix_solve(floatx, [[1],[1],[1],[1]]).eval())

[[23 12  4  3]
 [ 6  3  3  2]
 [ 1  7 23  7]
 [ 7  2  8  6]]
---matmul---
[[ 613  172  521  175]
 [2950  791  773  912]
 [ 221   90  367  181]
 [1180  479 2057  951]]
--matrix determinant--
84.0
----matrix solve----
[[ -3.66666651]
 [ 18.52380943]
 [ -0.4761906 ]
 [ -3.6190474 ]]


### REDUCTION
Reduction is an operation that applies an operation across one of the tensor's dimensions, 
leaving it with one less dimension.

In [28]:
sess = tf.InteractiveSession()

x = tf.constant( [ [1,46,8,2],[98,53,12,4],[5,3,13,6],[35,2,87,1]  ])

print("reduce por fila")
print(tf.reduce_max(x,reduction_indices=1).eval())

print("reduce mean por fila")
print(tf.reduce_mean(x,reduction_indices=1).eval())


reduce por fila
[46 98 13 87]
reduce mean por fila
[14 41  6 31]


### Sequences

In [29]:
sess = tf.InteractiveSession() 
x = tf.constant([[2, 5, 3, -5], 
                 [0, 3,-2,  5], 
                 [4, 3, 5,  3], 
                 [6, 1, 4,  0]]) 

listx = tf.constant([1,2,3,4,5,6,7,8]) 
listy = tf.constant([4,5,8,9]) 

In [33]:
print(tf.arg_min(x,1).eval()) # Position of the maximum value of columns 

print(tf.argmax(x, 1).eval()) # Position of the minimum value of rows

[3 2 1 3]
[1 3 2 0]


### Tensor shape transformations

In [34]:
sess = tf.InteractiveSession() 
x = tf.constant([  #rank two tensor
  [2, 5, 3, -5], 
  [0, 3,-2,  5], 
  [4, 3, 5,  3],  
  [6, 1, 4,  0]]) 

In [41]:
print(tf.shape(x).eval()) # Shape of the tensor

print(tf.size(x).eval()) #number of items that has a tensor

print(tf.rank(x).eval()) #rank of a tensor

print(tf.reshape(x,[8,2]).eval()) #reshape a tensor to o 8 rows and 2 columns (Solo sirve si tienen el mismo size )

[4 4]
16
2
[[ 2  5]
 [ 3 -5]
 [ 0  3]
 [-2  5]
 [ 4  3]
 [ 5  3]
 [ 6  1]
 [ 4  0]]


In [46]:
new_x = tf.expand_dims(x,1).eval() #Expanding dims
print(tf.rank(new_x).eval())

3


In [47]:
new_x2 = tf.squeeze(new_x).eval() #Expanding dims
print(tf.rank(new_x2).eval())

2


### TENSOR SLICING AND JOINING

In [58]:
sess = tf.InteractiveSession() 
t_matrix = tf.constant([ [1,2,3], 
                         [4,5,6], 
                         [7,8,9] ]) 

t_array = tf.constant([1,2,3,4,9,8,6,5]) 
t_array2= tf.constant([2,3,4,5,6,7,8,9]) 
 
print(tf.slice(t_matrix, [1, 1], [2,2]).eval()) # cutting an slice 

print(tf.slice(t_matrix, [1, 2], [1,1]).eval()) # cutting an slice 

[[5 6]
 [8 9]]
[[6]]


In [63]:
n,d =tf.split(0, 2, t_array) # splitting the array in two
print(n)
print(d)

Tensor("split_4:0", shape=(4,), dtype=int32)
Tensor("split_4:1", shape=(4,), dtype=int32)
